package com.app.gramaticas.sqlkv;


//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------


/** CUP generated interface containing symbol constants. */
public interface symbol {
  /* terminals */
  public static final int AND = 16;
  public static final int VALOR_NUMERICO = 19;
  public static final int MAYOR_IGUAL_QUE = 14;
  public static final int REPORTE = 3;
  public static final int OR = 17;
  public static final int IGUAL = 13;
  public static final int MENOR_IGUAL_QUE = 15;
  public static final int VALOR_CADENA = 21;
  public static final int NOT = 18;
  public static final int MAYOR_QUE = 12;
  public static final int COMILLAS = 20;
  public static final int ID = 6;
  public static final int POR = 5;
  public static final int FILTRAR = 4;
  public static final int MENOR_QUE = 11;
  public static final int EOF = 0;
  public static final int TIEMPO = 7;
  public static final int TRIVIA = 10;
  public static final int error = 1;
  public static final int USUARIO = 8;
  public static final int SELECCIONAR = 2;
  public static final int PUNTEO = 9;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "SELECCIONAR",
  "REPORTE",
  "FILTRAR",
  "POR",
  "ID",
  "TIEMPO",
  "USUARIO",
  "PUNTEO",
  "TRIVIA",
  "MENOR_QUE",
  "MAYOR_QUE",
  "IGUAL",
  "MAYOR_IGUAL_QUE",
  "MENOR_IGUAL_QUE",
  "AND",
  "OR",
  "NOT",
  "VALOR_NUMERICO",
  "COMILLAS",
  "VALOR_CADENA"
  };
public static final int VALOR_NUMERO = 0;
}

