
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.app.gramaticas.xson;

/** CUP generated interface containing symbol constants. */
public interface symbol {
  /* terminals */
  public static final int REALIZAR_SOLICITUD = 19;
  public static final int FIN_SOLICITUD = 17;
  public static final int INTERROGACION = 9;
  public static final int ID_TRIVIA = 36;
  public static final int NOMBRE = 26;
  public static final int ELIMINAR_TRIVIA = 41;
  public static final int CHECKBOX = 54;
  public static final int FIN_ETIQUETA = 16;
  public static final int RESPUESTA = 49;
  public static final int DOS_PUNTOS = 7;
  public static final int CORCHETE_DER = 6;
  public static final int INDICE = 62;
  public static final int FECHA = 68;
  public static final int MODIFICAR_USUARIO = 29;
  public static final int LLAVE_IZQ = 3;
  public static final int IGUAL = 12;
  public static final int USUARIO = 24;
  public static final int MODIFICAR_TRIVIA = 42;
  public static final int VERSION1 = 13;
  public static final int PREGUNTA = 67;
  public static final int VALOR_CADENA = 63;
  public static final int VERSION = 11;
  public static final int TRIVIA = 46;
  public static final int USUARIO_NUEVO = 22;
  public static final int ID = 45;
  public static final int FICHERO = 56;
  public static final int IDS = 66;
  public static final int INICIO_SOLICITUD = 14;
  public static final int EOF = 0;
  public static final int INICIO_ETIQUETA = 15;
  public static final int CLASE = 47;
  public static final int COMILLAS = 2;
  public static final int error = 1;
  public static final int COMA = 8;
  public static final int REALIZAR_SOLICITUDES = 18;
  public static final int ELIMINAR_USUARIO = 33;
  public static final int FECHA_MODIFICACION = 32;
  public static final int PASSWORD = 25;
  public static final int FECHA_CREACION = 28;
  public static final int USUARIO_CREACION = 39;
  public static final int TEMA = 40;
  public static final int FICHEROS = 58;
  public static final int TIEMPO_PREGUNTA = 38;
  public static final int NUEVO_PASSWORD = 31;
  public static final int RADIO = 55;
  public static final int LLAVE_DER = 4;
  public static final int PARAMETROS_COMPONENTE = 44;
  public static final int INSTITUCION = 27;
  public static final int MODIFICAR_COMPONENTE = 51;
  public static final int FIN_SOLICITUDES_REALIZADA = 21;
  public static final int PARAMETROS_TRIVIA = 35;
  public static final int ELIMINAR_COMPONENTE = 50;
  public static final int CORCHETE_IZQ = 5;
  public static final int USUARIO_ANTIGUO = 30;
  public static final int FIN_SOLICITUD_REALIZADA = 20;
  public static final int COMBO = 57;
  public static final int AGREGAR_COMPONENTE = 43;
  public static final int VALOR_NUMERO = 64;
  public static final int NUEVA_TRIVIA = 37;
  public static final int DATOS_USUARIO = 23;
  public static final int COLUMNAS = 61;
  public static final int XSON = 10;
  public static final int FILAS = 60;
  public static final int AREA_TEXTO = 53;
  public static final int CAMPO_TEXTO = 52;
  public static final int LOGIN_USUARIO = 34;
  public static final int OPTIONS = 65;
  public static final int TEXTO_VISIBLE = 48;
  public static final int OPCIONES = 59;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "COMILLAS",
  "LLAVE_IZQ",
  "LLAVE_DER",
  "CORCHETE_IZQ",
  "CORCHETE_DER",
  "DOS_PUNTOS",
  "COMA",
  "INTERROGACION",
  "XSON",
  "VERSION",
  "IGUAL",
  "VERSION1",
  "INICIO_SOLICITUD",
  "INICIO_ETIQUETA",
  "FIN_ETIQUETA",
  "FIN_SOLICITUD",
  "REALIZAR_SOLICITUDES",
  "REALIZAR_SOLICITUD",
  "FIN_SOLICITUD_REALIZADA",
  "FIN_SOLICITUDES_REALIZADA",
  "USUARIO_NUEVO",
  "DATOS_USUARIO",
  "USUARIO",
  "PASSWORD",
  "NOMBRE",
  "INSTITUCION",
  "FECHA_CREACION",
  "MODIFICAR_USUARIO",
  "USUARIO_ANTIGUO",
  "NUEVO_PASSWORD",
  "FECHA_MODIFICACION",
  "ELIMINAR_USUARIO",
  "LOGIN_USUARIO",
  "PARAMETROS_TRIVIA",
  "ID_TRIVIA",
  "NUEVA_TRIVIA",
  "TIEMPO_PREGUNTA",
  "USUARIO_CREACION",
  "TEMA",
  "ELIMINAR_TRIVIA",
  "MODIFICAR_TRIVIA",
  "AGREGAR_COMPONENTE",
  "PARAMETROS_COMPONENTE",
  "ID",
  "TRIVIA",
  "CLASE",
  "TEXTO_VISIBLE",
  "RESPUESTA",
  "ELIMINAR_COMPONENTE",
  "MODIFICAR_COMPONENTE",
  "CAMPO_TEXTO",
  "AREA_TEXTO",
  "CHECKBOX",
  "RADIO",
  "FICHERO",
  "COMBO",
  "FICHEROS",
  "OPCIONES",
  "FILAS",
  "COLUMNAS",
  "INDICE",
  "VALOR_CADENA",
  "VALOR_NUMERO",
  "OPTIONS",
  "IDS",
  "PREGUNTA",
  "FECHA"
  };
}

