
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.app.gramaticas.db;

/** CUP generated interface containing symbol constants. */
public interface simbol {
  /* terminals */
  public static final int REGISTRO = 38;
  public static final int ID_TRIVIA = 34;
  public static final int NOMBRE = 7;
  public static final int CHECKBOX = 19;
  public static final int DOS_PUNTOS = 31;
  public static final int RESPUESTA = 17;
  public static final int CORCHETE_DER = 43;
  public static final int ESTRUCTURA = 37;
  public static final int INDICE = 27;
  public static final int FECHA = 12;
  public static final int DBREGISTRO = 41;
  public static final int LLAVE_IZQ = 29;
  public static final int USUARIO = 3;
  public static final int RESPUESTAS = 44;
  public static final int PREGUNTA = 13;
  public static final int VALOR_CADENA = 2;
  public static final int TRIVIA = 9;
  public static final int DBUSUARIO = 40;
  public static final int ID = 32;
  public static final int FICHERO = 22;
  public static final int IDS = 35;
  public static final int EOF = 0;
  public static final int CLASE = 14;
  public static final int COMILLAS = 28;
  public static final int error = 1;
  public static final int COMA = 33;
  public static final int FECHA_MODIFICACION = 45;
  public static final int PASSWORD = 5;
  public static final int FECHA_CREACION = 46;
  public static final int USUARIO_CREACION = 4;
  public static final int TEMA = 11;
  public static final int RADIO = 20;
  public static final int LLAVE_DER = 30;
  public static final int INSTITUCION = 8;
  public static final int CORCHETE_IZQ = 42;
  public static final int COMBO = 21;
  public static final int VALOR_NUMERO = 36;
  public static final int TIEMPO = 10;
  public static final int DBTRIVIA = 39;
  public static final int COLUMNAS = 25;
  public static final int FILAS = 24;
  public static final int AREA_TEXTO = 18;
  public static final int VISIBLE = 16;
  public static final int CAMPO_TEXTO = 15;
  public static final int PUNTEO = 47;
  public static final int OPTIONS = 26;
  public static final int TEXTO_VISIBLE = 6;
  public static final int OPCIONES = 23;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "VALOR_CADENA",
  "USUARIO",
  "USUARIO_CREACION",
  "PASSWORD",
  "TEXTO_VISIBLE",
  "NOMBRE",
  "INSTITUCION",
  "TRIVIA",
  "TIEMPO",
  "TEMA",
  "FECHA",
  "PREGUNTA",
  "CLASE",
  "CAMPO_TEXTO",
  "VISIBLE",
  "RESPUESTA",
  "AREA_TEXTO",
  "CHECKBOX",
  "RADIO",
  "COMBO",
  "FICHERO",
  "OPCIONES",
  "FILAS",
  "COLUMNAS",
  "OPTIONS",
  "INDICE",
  "COMILLAS",
  "LLAVE_IZQ",
  "LLAVE_DER",
  "DOS_PUNTOS",
  "ID",
  "COMA",
  "ID_TRIVIA",
  "IDS",
  "VALOR_NUMERO",
  "ESTRUCTURA",
  "REGISTRO",
  "DBTRIVIA",
  "DBUSUARIO",
  "DBREGISTRO",
  "CORCHETE_IZQ",
  "CORCHETE_DER",
  "RESPUESTAS",
  "FECHA_MODIFICACION",
  "FECHA_CREACION",
  "PUNTEO"
  };
}

