
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.app.gramaticas.db;

/** CUP generated interface containing symbol constants. */
public interface simbol {
  /* terminals */
  public static final int REGISTRO = 37;
  public static final int ID_TRIVIA = 33;
  public static final int DB = 38;
  public static final int NOMBRE = 7;
  public static final int CHECKBOX = 18;
  public static final int DOS_PUNTOS = 30;
  public static final int RESPUESTA = 16;
  public static final int ESTRUCTURA = 36;
  public static final int INDICE = 26;
  public static final int DBREGISTRO = 42;
  public static final int LLAVE_IZQ = 28;
  public static final int USUARIO = 3;
  public static final int RESPUESTAS = 45;
  public static final int VALOR_CADENA = 2;
  public static final int TRIVIA = 10;
  public static final int DBUSUARIO = 41;
  public static final int ID = 31;
  public static final int FICHERO = 21;
  public static final int IDS = 34;
  public static final int PARENT_IZQ = 43;
  public static final int EOF = 0;
  public static final int CLASE = 13;
  public static final int COMILLAS = 27;
  public static final int error = 1;
  public static final int COMA = 32;
  public static final int PASSWORD = 5;
  public static final int FECHA_CREACION = 9;
  public static final int USUARIO_CREACION = 4;
  public static final int TEMA = 12;
  public static final int RADIO = 19;
  public static final int PUNTO = 39;
  public static final int LLAVE_DER = 29;
  public static final int INSTITUCION = 8;
  public static final int COMBO = 20;
  public static final int VALOR_NUMERO = 35;
  public static final int TIEMPO = 11;
  public static final int DBTRIVIA = 40;
  public static final int COLUMNAS = 24;
  public static final int PARENT_DER = 44;
  public static final int FILAS = 23;
  public static final int AREA_TEXTO = 17;
  public static final int VISIBLE = 15;
  public static final int CAMPO_TEXTO = 14;
  public static final int OPTIONS = 25;
  public static final int TEXTO_VISIBLE = 6;
  public static final int OPCIONES = 22;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "VALOR_CADENA",
  "USUARIO",
  "USUARIO_CREACION",
  "PASSWORD",
  "TEXTO_VISIBLE",
  "NOMBRE",
  "INSTITUCION",
  "FECHA_CREACION",
  "TRIVIA",
  "TIEMPO",
  "TEMA",
  "CLASE",
  "CAMPO_TEXTO",
  "VISIBLE",
  "RESPUESTA",
  "AREA_TEXTO",
  "CHECKBOX",
  "RADIO",
  "COMBO",
  "FICHERO",
  "OPCIONES",
  "FILAS",
  "COLUMNAS",
  "OPTIONS",
  "INDICE",
  "COMILLAS",
  "LLAVE_IZQ",
  "LLAVE_DER",
  "DOS_PUNTOS",
  "ID",
  "COMA",
  "ID_TRIVIA",
  "IDS",
  "VALOR_NUMERO",
  "ESTRUCTURA",
  "REGISTRO",
  "DB",
  "PUNTO",
  "DBTRIVIA",
  "DBUSUARIO",
  "DBREGISTRO",
  "PARENT_IZQ",
  "PARENT_DER",
  "RESPUESTAS"
  };
}

